#!/bin/bash

STATUS=$(cat /sys/class/power_supply/BAT1/status)

if [[ $STATUS == "Discharging" ]]; then
	case $(cat tdp) in
		"TDP1")
		# TDP 2
		cpupower frequency-set -g ondemand
		ryzenadj --stapm-limit=35000 --fast-limit=40000 --slow-limit=30000 --tctl-temp=85 --vrmmax-current=40000
		xsetroot -name "Setting TDP to 30W"
		echo TDP2 > tdp
		;;
		"TDP2")
		# TDP 1
		ryzenadj --stapm-limit=30000 --fast-limit=35000 --slow-limit=25000 --tctl-temp=80 --vrmmax-current=40000
		xsetroot -name "Setting TDP to 25W"
		echo TDP1 > tdp
		;;
		*)
		# TDP 1
		ryzenadj --stapm-limit=10000 --fast-limit=10000 --slow-limit=10000 --tctl-temp=65 --vrmmax-current=10000
		cpupower frequency-set -g powersave
		xsetroot -name "Setting TDP to 25W"
		echo TDP1 > tdp
		;;
	esac

elif [[ "$STATUS" = "Charging" || "$STATUS" = "Full" || "$STATUS" = "Unknown"  ]]; then
	case $(cat tdp) in
		"TDP1")
		# TDP 2
		ryzenadj --stapm-limit=45000 --fast-limit=40000 --slow-limit=40000 --tctl-temp=85 --vrmmax-current=45000
		xsetroot -name "Setting TDP to 40W"
		echo TDP2 > tdp
		;;
		"TDP2")
		# TDP 3
		ryzenadj --stapm-limit=50000 --fast-limit=55000 --slow-limit=45000 --tctl-temp=85 --vrmmax-current=50000
		xsetroot -name "Setting TDP to 45W"
		echo TDP3 > tdp
		;;
		"TDP3")
		# TDP 4
		ryzenadj --stapm-limit=70000 --fast-limit=70000 --slow-limit=70000 --tctl-temp=95 --vrmmax-current=70000
		xsetroot -name "Setting TDP to 70W"
		echo TDP4 > tdp
		;;
		*)
		# TDP 1
		ryzenadj --stapm-limit=30000 --fast-limit=35000 --slow-limit=25000 --tctl-temp=80 --vrmmax-current=40000
		xsetroot -name "Setting TDP to 25W"
		echo TDP1 > tdp
		;;
	esac
else
	xsetroot -name "UNKNOWN ERROR OCCURED"
fi
